// Deterministic mock data for the Dashboard. A given domain string always
// produces the same numbers, so the UI never flickers across re-renders.
// Swap with real integrations later.

export type VitalBand = "good" | "needs-improvement" | "poor";

export type WebVital = {
  id: "lcp" | "inp" | "cls";
  label: string;
  valueLabel: string;
  target: string;
  band: VitalBand;
  helper: string;
};

export type Keyword = {
  keyword: string;
  position: number;
  delta: number;
  volume: number;
};

export type IssueSeverity = "critical" | "warning" | "info";

export type Issue = {
  id: string;
  title: string;
  severity: IssueSeverity;
  count: number;
  detail: string;
  category: "technical" | "content" | "meta" | "links";
};

export type DashboardData = {
  score: number;
  scoreBand: "strong" | "fair" | "needs-work";
  scannedAgo: string;
  indexedPages: number;
  crawlErrors: number;
  webVitals: WebVital[];
  keywords: Keyword[];
  issues: Issue[];
};

// Tiny deterministic PRNG seeded from a string. Good enough for mock data —
// we just need stability, not cryptographic quality.
const hashSeed = (s: string) => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
};

const mulberry32 = (seed: number) => () => {
  let t = (seed = (seed + 0x6d2b79f5) >>> 0);
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

const pick = <T>(rnd: () => number, list: readonly T[]): T =>
  list[Math.floor(rnd() * list.length)];

const intBetween = (rnd: () => number, min: number, max: number) =>
  Math.floor(rnd() * (max - min + 1)) + min;

const KEYWORD_POOL = [
  "seo agent",
  "ai seo tool",
  "automated seo audit",
  "keyword research ai",
  "ai marketing automation",
  "on page seo audit",
  "technical seo checker",
  "content optimization ai",
  "seo copywriting tool",
  "site audit software",
  "rank tracking tool",
  "seo reporting dashboard",
  "link building ai",
  "serp analysis tool",
  "meta description generator",
];

const ISSUE_POOL: Omit<Issue, "count">[] = [
  {
    id: "missing-meta-desc",
    title: "Pages missing meta description",
    severity: "warning",
    detail: "Pages without a meta description get a snippet auto-generated by Google, usually less compelling.",
    category: "meta",
  },
  {
    id: "duplicate-h1",
    title: "Duplicate H1 tags detected",
    severity: "warning",
    detail: "Multiple pages share the same H1. Confuses search engines about the primary topic of each page.",
    category: "content",
  },
  {
    id: "slow-lcp",
    title: "Pages with slow LCP (> 4s)",
    severity: "critical",
    detail: "Largest Contentful Paint over 4s hurts rankings and bounce rate. Usually caused by large hero images or blocking scripts.",
    category: "technical",
  },
  {
    id: "broken-internal-links",
    title: "Broken internal links",
    severity: "critical",
    detail: "Links pointing to 404 pages leak link equity and frustrate users and crawlers.",
    category: "links",
  },
  {
    id: "thin-content",
    title: "Thin content pages (< 300 words)",
    severity: "warning",
    detail: "Pages with minimal copy rarely rank. Either expand them or consolidate into stronger pages with 301s.",
    category: "content",
  },
  {
    id: "missing-alt",
    title: "Images missing alt text",
    severity: "info",
    detail: "Alt text improves accessibility and image search rankings. Every decorative image should still have alt=\"\".",
    category: "technical",
  },
  {
    id: "title-length",
    title: "Title tags outside 30–60 chars",
    severity: "info",
    detail: "Titles that are too short waste SERP real estate; too long get truncated.",
    category: "meta",
  },
  {
    id: "no-canonical",
    title: "Pages missing canonical tag",
    severity: "warning",
    detail: "Without canonicals, parameter variants and near-duplicates compete with each other for the same ranking.",
    category: "technical",
  },
];

const bandFromValue = (
  value: number,
  good: number,
  poor: number
): VitalBand => {
  if (value <= good) return "good";
  if (value <= poor) return "needs-improvement";
  return "poor";
};

export const getDashboardData = (domain: string): DashboardData => {
  const rnd = mulberry32(hashSeed(domain));

  // Core Web Vitals — realistic ranges.
  const lcpMs = intBetween(rnd, 1600, 4200);
  const inpMs = intBetween(rnd, 80, 380);
  const clsRaw = Math.round(rnd() * 0.35 * 100) / 100;

  const webVitals: WebVital[] = [
    {
      id: "lcp",
      label: "Largest Contentful Paint",
      valueLabel: `${(lcpMs / 1000).toFixed(1)}s`,
      target: "≤ 2.5s",
      band: bandFromValue(lcpMs, 2500, 4000),
      helper: "How fast the main content paints.",
    },
    {
      id: "inp",
      label: "Interaction to Next Paint",
      valueLabel: `${inpMs}ms`,
      target: "≤ 200ms",
      band: bandFromValue(inpMs, 200, 500),
      helper: "Responsiveness to taps and clicks.",
    },
    {
      id: "cls",
      label: "Cumulative Layout Shift",
      valueLabel: clsRaw.toFixed(2),
      target: "≤ 0.10",
      band: bandFromValue(clsRaw, 0.1, 0.25),
      helper: "How much the layout shifts while loading.",
    },
  ];

  // Keywords — pick 10 distinct from the pool with believable ranking curves.
  const keywordSlice = [...KEYWORD_POOL]
    .sort(() => rnd() - 0.5)
    .slice(0, 10);
  const keywords: Keyword[] = keywordSlice
    .map((keyword, i) => {
      const position = intBetween(rnd, 1 + i * 2, 12 + i * 3);
      const delta = intBetween(rnd, -4, 6);
      const volume = [110, 210, 390, 580, 880, 1200, 1900, 2600, 3400, 4800][
        intBetween(rnd, 0, 9)
      ];
      return { keyword, position, delta, volume };
    })
    .sort((a, b) => a.position - b.position);

  // Issues — shuffle + assign realistic counts by severity.
  const issues: Issue[] = [...ISSUE_POOL]
    .sort(() => rnd() - 0.5)
    .slice(0, 6)
    .map((base) => ({
      ...base,
      count:
        base.severity === "critical"
          ? intBetween(rnd, 1, 8)
          : base.severity === "warning"
            ? intBetween(rnd, 2, 24)
            : intBetween(rnd, 5, 60),
    }))
    .sort((a, b) => {
      const order: Record<IssueSeverity, number> = {
        critical: 0,
        warning: 1,
        info: 2,
      };
      return order[a.severity] - order[b.severity];
    });

  // Overall score — inverse-weighted by band severity + issue severity.
  const vitalPenalty = webVitals.reduce((sum, v) => {
    if (v.band === "good") return sum;
    if (v.band === "needs-improvement") return sum + 6;
    return sum + 12;
  }, 0);
  const issuePenalty = issues.reduce((sum, i) => {
    if (i.severity === "critical") return sum + 8;
    if (i.severity === "warning") return sum + 3;
    return sum + 1;
  }, 0);
  const rawScore = Math.max(30, Math.min(99, 95 - vitalPenalty - issuePenalty));
  const scoreBand: DashboardData["scoreBand"] =
    rawScore >= 80 ? "strong" : rawScore >= 60 ? "fair" : "needs-work";

  const scannedAgo = pick(rnd, [
    "2 minutes ago",
    "18 minutes ago",
    "1 hour ago",
    "4 hours ago",
  ]);
  const indexedPages = intBetween(rnd, 38, 340);
  const crawlErrors = intBetween(rnd, 0, 12);

  return {
    score: rawScore,
    scoreBand,
    scannedAgo,
    indexedPages,
    crawlErrors,
    webVitals,
    keywords,
    issues,
  };
};

// Turn a clicked dashboard item into a natural-language chat prompt scoped
// to the active domain. Keeps the "AI recommends fixes" UX centralized.

export const promptForVital = (vital: WebVital, domain: string) =>
  `My ${vital.label} on ${domain} is ${vital.valueLabel} (target: ${vital.target}) — currently flagged as "${vital.band}". Walk me through the most impactful fixes, in priority order.`;

export const promptForKeyword = (kw: Keyword, domain: string) => {
  const direction = kw.delta > 0 ? `up ${kw.delta}` : kw.delta < 0 ? `down ${Math.abs(kw.delta)}` : "flat";
  return `For "${kw.keyword}" on ${domain} I'm ranking at position ${kw.position} (${direction} this week, search volume ~${kw.volume}/mo). What's the fastest realistic path to the top 3?`;
};

export const promptForIssue = (issue: Issue, domain: string) =>
  `On ${domain} I have ${issue.count} instance${issue.count === 1 ? "" : "s"} of "${issue.title}" (${issue.severity}). ${issue.detail} How should I fix this?`;
